### ISSUE TITLE
Support for adding divider's in the sidebar.

### ISSUE THREAD

**Issue by passhley** [UpliftGames/moonwave#34]
Currently all of the doc's you write all just go straight into the sidebar. It'd be really great if we could have dividers to
separate content. Such as separating class modules from system type modules

**Comment by evaera** [comment]
Thinking we could potentially allow `classOrder` to be like this:

```toml
[[classOrder]]
section = "Section name"
classes = ["Class1", "Class2"]

[[classOrder]]
section = "Section name 2"
classes = ["Class3", "Class4"]
```
