### ISSUE TITLE
Allow API section expansion configuration

### ISSUE THREAD

**Issue by LastTalon** [UpliftGames/moonwave#63]
Currently all API sections begin collapsed, but it would be great if we could config that.

Something along the lines of:

```toml
[[classOrder]]
section = "Section"
expand = true
classes = ["Class1", "Class2"]
```
